version: '3'
services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: as1054
      MYSQL_DATABASE: spring
    networks:
      - springboot-network

  app:
    container_name: springboot-container
    image: springboot-image
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./build/libs/SpringResult-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
